# Generated by Django 4.1.3 on 2023-01-10 08:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('superCategory', models.CharField(max_length=50)),
                ('subCategories', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=420, size=20)),
                ('color', models.CharField(max_length=15)),
                ('brandName', models.CharField(max_length=25)),
                ('availableSize', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=220, size=20)),
                ('age', models.CharField(max_length=5)),
                ('season', models.CharField(max_length=10)),
            ],
        ),
    ]
