# Generated by Django 4.1.3 on 2023-01-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBase',
        ),
    ]
