# Generated by Django 3.2.16 on 2023-01-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
