# Generated by Django 3.2.16 on 2023-01-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_database_userspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='UserSpace',
        ),
    ]
