# Generated by Django 3.2.16 on 2023-02-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_database_userspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspace',
            name='wishlist',
            field=models.TextField(),
        ),
    ]
