# Generated by Django 3.2.16 on 2023-02-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userspace_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSpace',
        ),
    ]
