# Generated by Django 3.2.16 on 2023-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_userspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('wishlist', models.TextField()),
                ('cart', models.TextField()),
            ],
        ),
    ]
