# Generated by Django 3.2.16 on 2023-02-01 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=20)),
                ('PASSWORD', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
