# Generated by Django 4.1.7 on 2023-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_vendoritems_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoritems',
            name='business_id',
            field=models.CharField(max_length=60),
        ),
    ]
