# Generated by Django 4.1.7 on 2023-04-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_vendoritems_business_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorItems',
        ),
    ]
